language: go

go:
  - 1.11.x
  - 1.12.x
  - tip

os:
  - linux
  - osx

env:
  global:
    - GO111MODULE=on

script:
  - go build
  - go test -v -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)