language: go

go:
  - 1.13.x
  - master

# Allow builds from tip to fail - they might be in an unstable state
jobs:
  allow_failures:
    - go: master

os:
  - linux
  - osx

env:
  global:
    - GO111MODULE=on

script:
  - go build
  - go test -v -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)
