name: golangci-lint

on: [ push ]
jobs:
  golangci:
    strategy:
      matrix:
        working-dir: [
          '.',
          'tenant'
        ]

    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
          check-latest: true
          cache-dependency-path: "**/*.sum"
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.64
          working-directory: ${{ matrix.working-dir }}