name: golangci-lint

on: [ push ]
jobs:
  golangci:
    strategy:
      matrix:
        submodule: [
          '',
          'tenant'
        ]

    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Install Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.25'
          check-latest: true
          cache-dependency-path: "**/*.sum"
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.4
          working-directory: ${{ matrix.submodule != '' && matrix.submodule || '.' }}