name: test

on: [ push, pull_request ]
jobs:
  test:
    strategy:
      matrix:
        go: [
          '1.23',
        ]
        os: [
          ubuntu-latest,
          macos-latest,
          windows-latest,
        ]

    runs-on: ${{ matrix.os }}

    env:
      OS: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Go ${{ matrix.go }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
          check-latest: true
      - name: Test
        run: go test -v -race -coverprofile="coverage.txt" -covermode=atomic $(go list -m | grep -v examples)
      - name: Upload code coverage
        uses: codecov/codecov-action@v4
        if: matrix.go == '1.23'
        with:
          file: coverage.txt
          token: ${{ secrets.CODECOV_TOKEN }}
          env_vars: OS

